export type MenuItem={category:string;number:string;name:string;description:string;price:number;variants?:{label:string;price:number}[];badge?:string;hot?:boolean};
const item=(category:string,number:string,name:string,description:string,price:number,variants?:{label:string;price:number}[]):MenuItem=>({category,number,name,description,price,variants});
const pizza=(number:string,name:string,description:string,alm:number,large=alm*2):MenuItem=>item("Pizza",number,name,description,alm,[{label:"Alm.",price:alm},{label:"3 Pers.",price:large}]);
export const menuItems:MenuItem[]=[
  pizza("1","Margherite","Tomatsauce, ost",70),pizza("2","Mozzarella","Tomatsauce, ost, pepperoni, champignon, artiskok, mozzarella",85),pizza("3","Quattro","Tomatsauce, ost, cheddar, gorgonzola, feta, mozzarella, soltørrede tomater",90),pizza("4","Hawaii","Tomatsauce, ost, skinke, ananas",75),pizza("5","Pepperoni","Tomatsauce, ost, fyldt pepperoni",75),pizza("6","Mafiosa","Tomatsauce, ost, skinke, bacon, champignon",75),pizza("7","Piccante","Tomatsauce, ost, skinke, bacon, oksekød, løg",80),pizza("8","Spaghetti","Tomatsauce, ost, pepperoni, løg, kødsauce, spaghetti",80),pizza("9","Frutti di Mare","Tomatsauce, ost, tun, majs",75),pizza("10","Sia","Tomatsauce, ost, rejer, muslinger, peberfrugt",80),pizza("11","Kebab","Tomatsauce, ost, kebab, løg, salat, dressing",80),pizza("12","Kylling","Tomatsauce, ost, kylling, champignon, salat, dressing",80),pizza("13","Darios","Tomatsauce, ost, skinke, pepperoni, bacon, pølse, rød peber",80),pizza("14","Danese","Tomatsauce, ost, oksekød, bacon, løg, pølse",80),pizza("15","Esotica","Tomatsauce, ost, kebab, løg, bacon, pølse, rød peber",80),pizza("16","Italia","Tomatsauce, ost, oksefilet, gorgonzola, løg",85),pizza("17","Pollo","Tomatsauce, ost, kylling, champignon, peberfrugt, artiskok",80),pizza("18","Stagioni","Tomatsauce, ost, skinke, bacon, champignon, løg",80),pizza("19","Zanobia","Tomatsauce, ost, kylling, champignon, majs, frisk tomat",80),pizza("20","Alita","Tomatsauce, ost, kebab, kylling, løg, pommes frites, dressing",80),item("Pizza","22","4 Seasons","Tomatsauce og ost med fire forskellige kombinationer af kebab, skinke, pepperoni og kylling",180,[{label:"3 Pers.",price:180}]),pizza("23","Vegetariana","Tomatsauce, ost, champignon, peberfrugt, løg, asparges, artiskok, frisk tomat",80),pizza("24","Din egen pizza","Vælg op til 5 ingredienser udover tomatsauce og ost",85),
  {...pizza("25","Spicy 1","Tomatsauce, ost, oksefilet, løg, oliven, jalapeños",75),category:"Spicy",hot:true},{...pizza("26","Spicy 2","Tomatsauce, ost, kebab, pepperoni, frisk chilipeber, pølse",75),category:"Spicy",hot:true},{...pizza("27","Spicy 3","Chili i tomatsauce, ost, kylling, champignon, caroline peber, bacon",75),category:"Spicy",hot:true},
  item("Børnepizza","28","Batman","Tomatsauce, ost, skinke, ananas",60),item("Børnepizza","29","Elsa","Tomatsauce, ost, fyldt pepperoni",60),item("Børnepizza","30","Mario","Tomatsauce, ost, kylling, majs",60),item("Børnepizza","31","Hulk","Tomatsauce, ost, kebab, champignon",60),
  item("Deep pan","32","Capricciosa","Tomatsauce, ost, skinke, champignon, ananas",80),item("Deep pan","33","Paplo","Tomatsauce, ost, kylling, champignon, bacon, pølse",85),item("Deep pan","34","Pirata","Tomatsauce, ost, pepperoni, rød peber",80),item("Deep pan","35","Veneziana","Tomatsauce, ost, oksekød, pølse, løg, bacon",85),item("Deep pan","36","Milano","Tomatsauce, ost, oksefilet, gorgonzola, jalapeños",85),item("Deep pan","37","4x4","Tomatsauce, ost, kebab, pepperoni, løg, oksekød",85),
  item("Indbagt","49","Calzone 1","Tomatsauce, ost, spaghetti, kødsauce",75),item("Indbagt","50","Calzone 2","Tomatsauce, ost, skinke, champignon, ananas",80),item("Indbagt","51","Calzone 3","Tomatsauce, ost, kylling, champignon, peber, bearnaisesauce",80),item("Indbagt","52","Calzone 4","Tomatsauce, ost, kebab, pepperoni, løg, jalapeños",80),
  item("UFO","53","UFO 1","Tomatsauce, ost, kebab, pepperoni, bacon, løg",85),item("UFO","54","UFO 2","Tomatsauce, ost, kylling, champignon, pølser",85),item("UFO","55","UFO 3","Tomatsauce, ost, skinke, oksekød, champignon",85),
  item("Pizza sandwich","56","Kebab sandwich","Ost, kebab, løg, salat, dressing",70),item("Pizza sandwich","57","Kyllinge sandwich","Ost, kylling, champignon, salat, dressing",70),item("Pizza sandwich","58","Skinke sandwich","Ost, skinke, bacon, salat, dressing",70),item("Pizza sandwich","59","Mix sandwich","Ost, kebab, kylling, løg, salat, dressing",70),
  item("Pita","60","Kebab pita","Kebab, salat, dressing",60),item("Pita","61","Kyllinge pita","Kylling, salat, dressing",60),item("Pita","62","Skinke pita","Skinke, salat, dressing",60),item("Pita","63","Tun pita","Tun, majs, salat, dressing",60),item("Pita","65","Falafel pita","Falafel, salat, dressing",60),
  item("Pasta","P1","Spaghetti Alla Bolognese","Spaghetti med kødsauce",75),item("Pasta","P2","Spaghetti Piccante","Spaghetti med skinke, bacon, løg og champignon i tomat-flødesauce",80),item("Pasta","P3","Fettuccine Con Pollo","Båndpasta med kylling, broccoli og karrysauce",80),item("Pasta","P4","Sia","Båndspaghetti, rejer og muslinger i tomat-flødesauce",80),item("Pasta","P5","Penne Della Casa","Penne-pasta med oksefilet og bacon i tomat-flødesauce",80),item("Pasta","P6","Spaghetti Alla Carbonara","Spaghetti, bacon og flødesauce",80),item("Pasta","P7","Tagliatelle Alla Italia","Båndpasta med oksekød, løg og frisk peber i tomat-flødesauce",80),item("Pasta","P8","Penne Alla Romana","Penne-pasta med bacon, skinke, løg og pesto i tomat-flødesauce",80),item("Pasta","P9","Penne Al Gorgonzola","Penne-pasta med oksefilet i gorgonzolasauce",80),item("Pasta","P10","Spaghetti Diavola","Spaghetti med fløde og kødsauce krydret med chili",80),item("Pasta","P11","Luksus pasta","Båndpasta med kylling, broccoli, champignon og chili i tomat-flødesauce",80),
  item("Rulle","66","Kebab rulle","Kebab, salat, dressing",65),item("Rulle","67","Kyllinge rulle","Kylling, salat, dressing",65),item("Rulle","68","Mix rulle","Kebab, kylling, salat, dressing",65),item("Rulle","69","Falafel rulle","Falafel, salat, dressing",65),
  item("Grill & brød","70","Hjemmebagt hvidløgsbrød","",50),item("Grill & brød","71","Hjemmebagt hvidløgsbrød med ost","",55),item("Grill & brød","72","Kebab mix","Kebab, kartoffelskiver, salat, tzatziki, dressing",75),item("Grill & brød","73","Kyllinge mix","Kylling, kartoffelskiver, salat, tzatziki, dressing",75),item("Grill & brød","74","Kylling og kebab mix","Kebab, kylling, kartoffelskiver, salat, tzatziki, dressing",80),item("Grill & brød","75","Pølse mix","Pølser, kartoffelskiver, salat, ketchup, remoulade",75),
  item("Nachos","77","Nachos kebab","Cheddar, salsa, guacamole, jalapeños",70),item("Nachos","78","Nachos kylling","Cheddar, salsa, guacamole, jalapeños",70),item("Nachos","79","Nachos oksekød","Cheddar, salsa, guacamole, jalapeños",70),
  item("Burger","80","Cheese burger · 200 g bøf","Ost, syltet agurk, løg, ketchup",55,[{label:"Alm.",price:55},{label:"Menu",price:90}]),item("Burger","81","Crispy burger","Salat, tomat, hvidløgsmayonnaise, burgerdressing",55,[{label:"Alm.",price:55},{label:"Menu",price:90}]),item("Burger","82","Smokey burger · 200 g bøf","Ost, bacon, syltet agurk, løg, tomat, BBQ-sauce",65,[{label:"Alm.",price:65},{label:"Menu",price:100}]),item("Burger","83","Jambo burger · 200 g bøf","Ost, bacon, salat, løg, tomat, burgerdressing",65,[{label:"Alm.",price:65},{label:"Menu",price:100}]),item("Burger","84","Nacho burger · 200 g bøf","Ost, chips, salat, jalapeños, salsa, burgerdressing",65,[{label:"Alm.",price:65},{label:"Menu",price:100}]),
  item("Snacks","86","4 stk. Chili cheese tops","",25),item("Snacks","87","4 stk. Mozzarella sticks","",25),item("Snacks","88","4 stk. Løgringe","",25),item("Snacks","89","4 stk. Kyllingenuggets","",25),item("Snacks","90","Spicy kurv 1","5 chili cheese tops, 5 kyllingenuggets, pommes frites",70),item("Snacks","91","Spicy kurv 2","5 mozzarella sticks, 5 løgringe, pommes frites",70),item("Snacks","92","Spicy family kurv","5 mozzarella sticks, 5 løgringe, 5 kyllingenuggets, 5 chili cheese tops, stor pommes frites",100),item("Snacks","93","Spicy box","Pommes frites, ost, jalapeños, chilisauce",50),item("Snacks","94","Pommes frites","Med 2 slags dip",30,[{label:"Lille",price:30},{label:"Stor",price:40}]),item("Snacks","95","Tzatziki","",35),item("Snacks","96","Hummus","",35),item("Snacks","97","Special spicy sauce","",10),
  item("Drikkevarer","D1","Coca-Cola 33 cl","",15),item("Drikkevarer","D2","Fanta 33 cl","",15),item("Drikkevarer","D3","Faxe Kondi 33 cl","",15),item("Drikkevarer","D4","Coca-Cola Zero 33 cl","",15),item("Drikkevarer","D5","Ayran","",15),item("Drikkevarer","D6","Carlsberg øl 33 cl","18+",15),item("Drikkevarer","D7","Coca-Cola 1,5 L","",35),item("Drikkevarer","D8","Fanta 1,5 L","",35),item("Drikkevarer","D9","Faxe Kondi 1,5 L","",35),item("Drikkevarer","D10","Coca-Cola Zero 1,5 L","Pris skal bekræftes",35),
];
export const categories=[...new Set(menuItems.map((entry)=>entry.category))];
