"use client";

import { useState } from "react";
import { categories, menuItems, type MenuItem } from "./menu-data";

type CartItem = MenuItem & { id:string; quantity:number; size:string; extras:{name:string;quantity:number;price:number}[]; note:string; unitPrice:number };
type Topping = { name:string; price:number };

const toppings:Topping[] = [
  ...["Kebab","Kylling","Pepperoni","Skinke","Pølse","Bacon","Tun","Oksefilet","Fyldt pepperoni","Oksekød","Ost","Salat","Caroline peber","Mozzarella","Cheddarost","Gorgonzola","Fetaost"].map((name)=>({name,price:10})),
  ...["Løg","Frisk tomat","Majs","Peberfrugt","Champignon","Asparges","Rød peber","Soltørrede tomater","Tomat-flødesauce","Broccoli","Artiskok","Ananas","Hvidløg","Chilipeber","Jalapeños","Dressing"].map((name)=>({name,price:5})),
];
export default function Home() {
  const [activeCategory, setActiveCategory] = useState("Pizza");
  const [cart, setCart] = useState<CartItem[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [checkout, setCheckout] = useState(false);
  const [orderType, setOrderType] = useState<"pickup"|"delivery">("pickup");
  const [selectedItem, setSelectedItem] = useState<MenuItem|null>(null);
  const [selectedSize, setSelectedSize] = useState("Alm.");
  const [selectedExtras, setSelectedExtras] = useState<Record<string,number>>({});
  const visibleItems = menuItems.filter((item) => item.category === activeCategory);
  const itemCount = cart.reduce((sum,item) => sum + item.quantity, 0);
  const subtotal = cart.reduce((sum,item) => sum + item.unitPrice * item.quantity, 0);
  const deliveryFee = orderType === "delivery" ? 25 : 0;
  const allowsExtras = (item:MenuItem) => ["Pizza","Spicy","Børnepizza","Deep pan","Indbagt","UFO"].includes(item.category);
  const itemBasePrice = selectedItem ? selectedItem.variants?.find((variant)=>variant.label===selectedSize)?.price ?? selectedItem.price : 0;
  const extrasPrice = toppings.reduce((sum,topping)=>sum+(selectedExtras[topping.name]||0)*topping.price,0);
  const openCustomizer = (item:MenuItem) => { setSelectedItem(item); setSelectedSize(item.variants?.[0]?.label||"Standard"); setSelectedExtras({}); };
  const updateExtra = (name:string,amount:number) => setSelectedExtras((current)=>({...current,[name]:Math.max(0,(current[name]||0)+amount)}));
  const confirmItem = () => { if(!selectedItem)return; const extras=toppings.filter((t)=>selectedExtras[t.name]>0).map((t)=>({...t,quantity:selectedExtras[t.name]})); const id=`${selectedItem.number}-${Date.now()}`; const hasVariant=Boolean(selectedItem.variants?.length); const details=[hasVariant?selectedSize:"",extras.map((extra)=>`${extra.quantity}× ${extra.name}`).join(", ")].filter(Boolean).join(" · "); setCart((current)=>[...current,{...selectedItem,name:`${selectedItem.name}${hasVariant?` · ${selectedSize}`:""}`,description:details,price:itemBasePrice+extrasPrice,id,quantity:1,size:hasVariant?selectedSize:"Standard",extras,note:"",unitPrice:itemBasePrice+extrasPrice}]); setSelectedItem(null); setCartOpen(true); };
  const changeQuantity = (number:string, amount:number) => setCart((current)=>current.map((item)=>item.number===number?{...item,quantity:item.quantity+amount}:item).filter((item)=>item.quantity>0));
  const openCart = () => { setCheckout(false); setCartOpen(true); };

  return <main>
    <header className="site-header">
      <a className="brand brand-logo" href="#top" aria-label="Spicy Pizza og Grill, forsiden"><img src="/spicy-logo.png" alt="Spicy Pizza & Grill"/></a>
      <nav aria-label="Hovedmenu"><a href="#menu">Menukort</a><a href="#about">Om os</a><a href="#contact">Kontakt</a></nav>
      <button className="button button-small cart-trigger" onClick={openCart}>Kurv <span>{itemCount}</span></button>
    </header>
    <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow"><i /> Vestergade 45 · Horsens</span><h1>Smagen må gerne <em>bide lidt.</em></h1><p>Sprøde pizzaer, saftige burgere og vores egen stærke sauce. Tilberedt frisk, når du bestiller.</p><div className="hero-actions"><a className="button" href="#menu">Bestil direkte</a><a className="text-link" href="tel:+4526432750">Ring 26 43 27 50 <span>→</span></a></div><div className="hero-meta"><div><strong>4,7</strong><span>★★★★★<small>Google rating</small></span></div><div><strong>20</strong><span>min.<small>Ca. afhentning</small></span></div></div></div><div className="hero-visual" aria-label="Frisk pizza med krydrede ingredienser"><div className="hero-tag"><span>Åben i dag</span><strong>16:00—23:00</strong></div><div className="round-label"><span>HORSENS</span><b>SPICY</b></div></div></section>
    <section className="marquee" aria-label="Restaurantens kvaliteter"><span>Friske råvarer</span><b>✦</b><span>Bestil direkte</span><b>✦</b><span>Hurtig afhentning</span><b>✦</b><span>Levering i Horsens</span></section>
    <section className="delivery-preview" aria-label="Leveringsinformation"><div className="delivery-icon">4 <small>KM</small></div><div><span>Levering i nærområdet</span><strong>Levering fra 25 kr.</strong><p>Op til 4 km fra restauranten · foreløbige demooplysninger</p></div><button onClick={openCart}>Vælg levering <b>→</b></button></section>
    <section className="menu-section" id="menu"><div className="section-heading"><div><span className="eyebrow"><i /> Vælg din favorit</span><h2>Hele menukortet</h2></div><p>Vælg mellem alle restaurantens kategorier, og tilpas din bestilling.</p></div><div className="category-tabs" role="tablist" aria-label="Menukategorier">{categories.map((category)=><button key={category} className={activeCategory===category?"active":""} onClick={()=>setActiveCategory(category)} role="tab" aria-selected={activeCategory===category}>{category}</button>)}</div><div className="menu-grid">{visibleItems.map((item)=><article className="menu-card order-card" key={`${item.category}-${item.number}`}><div className="menu-number">{item.number}</div><div className="menu-copy"><div className="menu-title"><h3>{item.name}</h3>{item.hot&&<span className="hot">STÆRK</span>}{item.badge&&<span className="badge">{item.badge}</span>}</div>{item.description&&<p>{item.description}</p>}</div><div className="menu-buy"><strong className="price">{item.variants&&item.variants.length>1?"Fra ":""}{item.price},–</strong><button onClick={()=>openCustomizer(item)} aria-label={`Vælg ${item.name}`}>+</button></div></article>)}</div><p className="demo-note">Priser og oplysninger er overført fra restaurantens nuværende menukort og skal bekræftes før lancering.</p></section>
    <section className="feature-section" id="about"><div className="feature-image"><span>Spicy siden<br/><strong>2021</strong></span></div><div className="feature-copy"><span className="eyebrow light"><i /> Lavet med kærlighed</span><h2>En lokal favorit i hjertet af Horsens.</h2><p>Hos Spicy Pizza & Grill handler det om god mad uden unødige omveje. Vi bruger friske råvarer, laver vores egen dressing og giver dig mulighed for at sammensætte pizzaen præcis, som du vil have den.</p><div className="feature-points"><div><span>01</span><strong>Frisklavet hver dag</strong></div><div><span>02</span><strong>Afhentning & levering</strong></div></div></div></section>
    <section className="order-banner"><span className="eyebrow light"><i /> Sulten?</span><h2>Aftensmaden er kun<br/>få klik væk.</h2><div><button className="button button-light" onClick={()=>document.querySelector("#menu")?.scrollIntoView()}>Start din bestilling</button><a className="text-link light-link" href="tel:+4526432750">Eller ring til os <span>→</span></a></div></section>
    <section className="food-control" aria-label="Fødevarekontrol"><div className="smiley-mark" aria-hidden="true">☺</div><div><span>Offentlig fødevarekontrol</span><h2>Se vores kontrolrapport</h2><p>Rapporten åbner direkte hos Fødevarestyrelsens officielle Find Smiley-side.</p></div><a href="https://www.findsmiley.dk/app/1279108" target="_blank" rel="noopener noreferrer">Se kontrolrapport <b>↗</b></a></section>
    <footer id="contact"><div className="footer-brand"><div className="brand brand-logo footer-logo"><img src="/spicy-logo.png" alt="Spicy Pizza & Grill"/></div><p>Pizza, pasta og grill i Horsens.</p></div><div><span className="footer-label">Besøg os</span><p>Vestergade 45<br/>8700 Horsens</p><a href="https://maps.google.com/?q=Vestergade+45+8700+Horsens">Find vej ↗</a></div><div><span className="footer-label">Kontakt</span><p><a href="tel:+4526432750">26 43 27 50</a><br/><a href="mailto:spicypizzagrill@gmail.com">spicypizzagrill@gmail.com</a></p></div><div><span className="footer-label">Åbningstider</span><p>Mandag: Lukket<br/>Tirsdag—søndag: 16—23</p></div><div className="footer-bottom"><span>© 2026 Spicy Pizza & Grill</span><span>Frontend-demo · oplysninger skal bekræftes</span></div></footer>

    {cartOpen && <><button className="cart-backdrop" onClick={()=>setCartOpen(false)} aria-label="Luk kurven"/><aside className="cart-panel" aria-label="Din bestilling" aria-live="polite"><div className="cart-head"><div><span>DIN BESTILLING</span><h2>{checkout?"Oplysninger":"Kurv"}</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Luk">×</button></div>{checkout?<div className="checkout-form"><button className="back-link" onClick={()=>setCheckout(false)}>← Tilbage til kurven</button><div className="order-toggle"><button className={orderType==="pickup"?"active":""} onClick={()=>setOrderType("pickup")}>Afhentning</button><button className={orderType==="delivery"?"active":""} onClick={()=>setOrderType("delivery")}>Levering</button></div><label>Navn<input type="text" placeholder="Dit fulde navn"/></label><label>Telefon<input type="tel" placeholder="Dit telefonnummer"/></label>{orderType==="delivery"&&<label>Leveringsadresse<input type="text" placeholder="Adresse i Horsens"/></label>}<label>Bemærkning<textarea placeholder="Fx ingen løg eller ekstra dressing"/></label><div className="checkout-summary"><span>Total</span><strong>{subtotal+deliveryFee},–</strong></div><button className="checkout-button" disabled>Betaling aktiveres efter aftale</button><p>Dette er et sikkert demoflow. Ingen oplysninger bliver sendt.</p></div>:<div className="cart-content">{cart.length===0?<div className="empty-cart"><span>0</span><h3>Kurven er tom</h3><p>Vælg noget lækkert fra menukortet.</p><button onClick={()=>setCartOpen(false)}>Se menukort</button></div>:<><div className="cart-items">{cart.map((item)=><div className="cart-item" key={item.number}><div><strong>{item.name}</strong><small>Nr. {item.number}</small></div><div className="quantity"><button onClick={()=>changeQuantity(item.number,-1)} aria-label={`Fjern en ${item.name}`}>−</button><span>{item.quantity}</span><button onClick={()=>changeQuantity(item.number,1)} aria-label={`Tilføj en ${item.name}`}>+</button></div><b>{item.price*item.quantity},–</b></div>)}</div><div className="cart-total"><span>Subtotal</span><strong>{subtotal},–</strong></div><button className="checkout-button" onClick={()=>setCheckout(true)}>Gå til bestilling <span>→</span></button><p className="cart-caption">Betaling og ordremodtagelse aktiveres efter aftale med restauranten.</p></>}</div>}</aside></>}
    {selectedItem && <><button className="cart-backdrop" onClick={()=>setSelectedItem(null)} aria-label="Luk tilpasning"/><section className="customizer" role="dialog" aria-modal="true" aria-label={`Tilpas ${selectedItem.name}`}>
      <div className="customizer-head"><div><span>NR. {selectedItem.number}</span><h2>{selectedItem.name}</h2><p>{selectedItem.description}</p></div><button onClick={()=>setSelectedItem(null)} aria-label="Luk">×</button></div>
      <div className="customizer-body">
        {selectedItem.variants&&selectedItem.variants.length>1&&<div className="customizer-section"><h3>Vælg variant</h3><div className="size-options">{selectedItem.variants.map((variant)=><button key={variant.label} className={selectedSize===variant.label?"active":""} onClick={()=>setSelectedSize(variant.label)}><span>{variant.label}</span><strong>{variant.price},–</strong></button>)}</div></div>}
        {allowsExtras(selectedItem)&&<div className="customizer-section"><h3>Ekstra tilbehør <small>valgfrit</small></h3><div className="toppings-grid">{toppings.map((topping)=><div className="topping-row" key={topping.name}><div><strong>{topping.name}</strong><small>+{topping.price},–</small></div><div className="topping-quantity"><button onClick={()=>updateExtra(topping.name,-1)} aria-label={`Fjern ${topping.name}`}>−</button><span>{selectedExtras[topping.name]||0}</span><button onClick={()=>updateExtra(topping.name,1)} aria-label={`Tilføj ${topping.name}`}>+</button></div></div>)}</div></div>}
      </div>
      <div className="customizer-footer"><div><span>Total for varen</span><strong>{itemBasePrice+extrasPrice},–</strong></div><button onClick={confirmItem}>Læg i kurven <span>→</span></button></div>
    </section></>}
  </main>;
}
